# Changes here will be overwritten by Copier
_commit: v3.3.0
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
codeowner_username: '@stkr22'
copyright_license: GPL-3.0
github_repository_name: private-assistant-iot-state-skill-py
github_username: stkr22
project_description: This package allows the querying of iot states via timescaledb.
project_name: Private Assistant IoT State Skill
publish_to_pypi: false
python_package_distribution_name: private-assistant-iot-state-skill
python_package_import_name: private_assistant_iot_state_skill
python_package_version: 0.1.3
use_containers: true
