# Changes here will be overwritten by Copier
_commit: v2.1.0
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
codeowner_username: '@stkr22'
copyright_license: GNU General Public License v3.0
github_repository_name: private-assistant-iot-state-skill-py
github_username: stkr22
project_description: This package allows the querying of iot states via timescaledb.
project_name: Private Assistant IoT State Skill
publish_to_pypi: false
python_package_distribution_name: private-assistant-iot-state-skill
python_package_import_name: private_assistant_iot_state_skill
use_containers: true
